"""Build a reusable data preprocessing pipeline for F5 RiskAI.

This pipeline prepares the raw stroke dataset for a future model training step.
It does NOT train any model, does not modify the raw data, and does not apply
oversampling/undersampling or SMOTE.

Pipeline steps for the feature matrix (target ``stroke`` is excluded):

* Continuous numeric features (``age``, ``avg_glucose_level``, ``bmi``)
  are standardised with :class:`~sklearn.preprocessing.StandardScaler`.
* Binary numeric features (``hypertension``, ``heart_disease``) are passed
  through unchanged (they are already 0/1 indicators, scaling adds no value).
* Categorical features are one-hot encoded with
  :class:`~sklearn.preprocessing.OneHotEncoder` configured with
  ``handle_unknown="ignore"`` so that unseen categories in future data do not
  raise errors (robust to new data, avoids leaking category knowledge from the
  fit set at prediction time).

Usage (CLI)::

    python scripts/preprocessing.py [--input PATH] [--output PATH]

The transformed features are saved to ``data/processed/`` together with the
corresponding list of transformed feature names.

.. warning::

    ``X_preprocessed.csv`` is generated by this script only to validate that
    the pipeline works and to inspect the transformation. It is produced by
    fitting the pipeline on the **full dataset**, so it MUST NOT be used
    directly to train the model (that would leak information and bias the
    evaluation).

    For real model training always apply a train/test split first and fit the
    pipeline only on the training split::

        Train/Test Split
               |
               v
        Pipeline.fit(Train)
               |
               v
        Pipeline.transform(Train/Test)

    so that no information from the test set leaks into training.
"""

from __future__ import annotations

import argparse
import json
import os

import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

RAW_DATA_PATH = os.path.join("data", "raw", "stroke_dataset.csv")
PROCESSED_DATA_PATH = os.path.join("data", "processed", "X_preprocessed.csv")
FEATURE_NAMES_PATH = os.path.join("data", "processed", "feature_names.json")

TARGET_COLUMN = "stroke"

CONTINUOUS_FEATURES = ["age", "avg_glucose_level", "bmi"]
BINARY_FEATURES = ["hypertension", "heart_disease"]
CATEGORICAL_FEATURES = [
    "gender",
    "ever_married",
    "work_type",
    "Residence_type",
    "smoking_status",
]

ALL_FEATURE_COLUMNS = BINARY_FEATURES + CONTINUOUS_FEATURES + CATEGORICAL_FEATURES


def build_preprocessing_pipeline() -> Pipeline:
    """Return a reusable ColumnTransformer wrapped in a scikit-learn Pipeline."""
    continuous_transformer = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
        ]
    )

    column_transformer = ColumnTransformer(
        transformers=[
            ("scale_continuous", continuous_transformer, CONTINUOUS_FEATURES),
            ("binary_passthrough", "passthrough", BINARY_FEATURES),
            ("encode_categorical", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES),
        ]
    )

    return Pipeline(steps=[("preprocess", column_transformer)])


def get_transformed_feature_names(
    pipeline: Pipeline, feature_names: list[str] | None = None
) -> list[str]:
    """Return the names of the columns produced after transformation.

    The pipeline must already be fitted so that the one-hot encoder knows its
    categories.
    """
    transformer: ColumnTransformer = pipeline.named_steps["preprocess"]
    names: list[str] = []

    for name, _, columns in transformer.transformers_:
        if name == "scale_continuous":
            names.extend(CONTINUOUS_FEATURES)
        elif name == "binary_passthrough":
            names.extend(BINARY_FEATURES)
        elif name == "encode_categorical":
            encoder: OneHotEncoder = transformer.named_transformers_[name]
            categories = encoder.categories_
            for column, cats in zip(columns, categories):
                names.extend(f"{column}_{cat}" for cat in cats)

    return names


def run_preprocessing(
    input_path: str = RAW_DATA_PATH,
    output_path: str = PROCESSED_DATA_PATH,
    feature_names_path: str = FEATURE_NAMES_PATH,
) -> dict:
    """Load raw data, fit the pipeline, and save the transformed features.

    Returns a small summary dict with the resulting shape and feature names.
    """
    df = pd.read_csv(input_path)

    X = df[ALL_FEATURE_COLUMNS]
    y = df[TARGET_COLUMN]

    pipeline = build_preprocessing_pipeline()
    X_transformed = pipeline.fit_transform(X)

    feature_names = get_transformed_feature_names(pipeline, ALL_FEATURE_COLUMNS)
    X_out = pd.DataFrame(X_transformed, columns=feature_names)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    X_out.to_csv(output_path, index=False)

    with open(feature_names_path, "w", encoding="utf-8") as fh:
        json.dump(feature_names, fh, indent=2)

    return {
        "rows": X_out.shape[0],
        "features": X_out.shape[1],
        "feature_names": feature_names,
        "target_non_null": int(y.notna().sum()),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Preprocess the stroke dataset.")
    parser.add_argument("--input", default=RAW_DATA_PATH, help="Raw CSV input path.")
    parser.add_argument("--output", default=PROCESSED_DATA_PATH, help="Processed CSV output path.")
    args = parser.parse_args()

    summary = run_preprocessing(input_path=args.input, output_path=args.output)
    print(f"Filas procesadas: {summary['rows']}")
    print(f"Features transformadas: {summary['features']}")
    print("Nombres de features:")
    for name in summary["feature_names"]:
        print(f"  - {name}")


if __name__ == "__main__":
    main()
