<script setup>
/**
 * Reports view — PDF report downloads for stored assessments
 * (GET /assessments + GET /assessments/{id}/report).
 *
 * States: LOADING / ERROR / EMPTY / SUCCESS. The PDF is generated by the
 * backend from the REAL persisted assessment/patient data (ReportLab) and is
 * served as an attachment; the list shows the newest assessments first.
 */
import { computed, onMounted, ref } from 'vue'

import { assessmentReportUrl, listAssessments } from '@/services/predictionService.js'
import { state, t } from '@/store.js'

const assessments = ref([])
const loading = ref(true)
const error = ref(null)

const isEmpty = computed(() => assessments.value.length === 0)

function formatDate(value) {
  if (!value) return '—'
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return '—'
  const pad = (n) => String(n).padStart(2, '0')
  return `${pad(d.getDate())}/${pad(d.getMonth() + 1)}/${d.getFullYear()}`
}

function reportUrl(id) {
  return assessmentReportUrl(id, state.language)
}

async function load() {
  loading.value = true
  error.value = null
  try {
    assessments.value = await listAssessments()
  } catch (err) {
    error.value = (err && err.message) || t('reportsError')
  } finally {
    loading.value = false
  }
}

onMounted(load)
</script>

<template>
  <div class="view">
    <div class="view__intro">
      <span class="view__kicker">{{ t('reportsEyebrow') }}</span>
      <h1 class="view__title">{{ t('reportsTitle') }}</h1>
      <p class="view__subtitle">{{ t('reportsSubtitle') }}</p>
    </div>

    <div v-if="loading" class="state-box" role="status">
      <span class="state-box__icon state-box__icon--spin" aria-hidden="true">⟳</span>
      {{ t('reportsLoading') }}
    </div>

    <div v-else-if="error" class="state-box">
      <span class="state-box__error">{{ error }}</span>
      <button class="state-box__retry" type="button" @click="load">
        {{ t('retry') }}
      </button>
    </div>

    <div v-else-if="isEmpty" class="empty">
      <svg class="empty__icon" viewBox="0 0 24 24" aria-hidden="true">
        <path
          d="M6 2h8l4 4v16H6z"
          fill="none"
          stroke="currentColor"
          stroke-width="1.6"
          stroke-linejoin="round"
        />
        <path d="M14 2v4h4" fill="none" stroke="currentColor" stroke-width="1.6" />
        <path d="M9 12h6M9 15h6M9 18h4" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" />
      </svg>
      <span class="empty__title">{{ t('reportsEmptyTitle') }}</span>
      <span class="empty__hint">{{ t('reportsEmptyHint') }}</span>
    </div>

    <ul v-else class="list">
      <li v-for="assessment in assessments" :key="assessment.id" class="item">
        <div class="item__body">
          <span class="item__title">{{ t('reportResult') }} · {{ (assessment.probability * 100).toFixed(1) }}%</span>
          <span class="item__sub">
            {{ t('reportGeneratedOn') }}: {{ formatDate(assessment.created_at) }} · {{ t('risk.probabilityLabel') }} {{ (assessment.probability * 100).toFixed(2) }}%
          </span>
        </div>
        <a
          class="item__action"
          :href="reportUrl(assessment.id)"
          :download="`informe_riskai_${assessment.id}.pdf`"
          target="_blank"
          rel="noopener"
        >
          <svg viewBox="0 0 24 24" aria-hidden="true">
            <path d="M12 3v12m0 0 4-4m-4 4-4-4M5 21h14" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
          {{ t('reportDownload') }}
        </a>
      </li>
    </ul>
  </div>
</template>

<style scoped>
.view__intro {
  margin-bottom: 22px;
}

.view__kicker {
  font-size: 12px;
  font-weight: var(--w-700);
  text-transform: uppercase;
  letter-spacing: 0.09em;
  color: var(--color-accent-strong);
}

.view__title {
  font-size: var(--fs-h1);
  margin-top: 6px;
}

.view__subtitle {
  margin-top: 8px;
  font-size: 15px;
  color: var(--color-ink-mute);
}

.state-box {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 12px;
  min-height: 160px;
  color: var(--color-ink-mute);
  background: var(--glass-bg);
  backdrop-filter: var(--glass-blur);
  -webkit-backdrop-filter: var(--glass-blur);
  border: var(--color-hairline);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-sm);
}

.state-box__icon {
  color: var(--color-accent-strong);
  font-size: 18px;
}

.state-box__icon--spin {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.state-box__error {
  color: var(--color-danger);
}

.state-box__retry {
  font-size: 12.5px;
  font-weight: var(--w-600);
  color: var(--color-primary);
  background: var(--color-active-bg);
  border: var(--color-hairline);
  border-radius: var(--radius-pill);
  padding: 6px 14px;
  cursor: pointer;
}

.empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 8px;
  min-height: 260px;
  max-width: 720px;
  text-align: center;
  background: var(--color-card-glass);
  border: 1px dashed var(--color-hairline-dark);
  border-radius: var(--radius-lg);
  padding: 32px 24px;
}

.empty__icon {
  width: 36px;
  height: 36px;
  color: var(--color-accent-strong);
  opacity: 0.7;
}

.empty__title {
  font-size: 15px;
  font-weight: var(--w-600);
  color: var(--color-primary);
}

.empty__hint {
  font-size: 13px;
  color: var(--color-ink-mute);
  max-width: 320px;
}

.list {
  display: flex;
  flex-direction: column;
  gap: 12px;
  list-style: none;
}

.item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  background: var(--glass-bg);
  backdrop-filter: var(--glass-blur);
  -webkit-backdrop-filter: var(--glass-blur);
  border: var(--color-hairline);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-sm);
  padding: 16px 18px;
}

.item__body {
  display: flex;
  flex-direction: column;
  gap: 3px;
  min-width: 0;
}

.item__title {
  font-size: 14.5px;
  font-weight: var(--w-600);
  color: var(--color-primary);
}

.item__sub {
  font-size: 12.5px;
  color: var(--color-ink-faint);
}

.item__action {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-size: 13px;
  font-weight: var(--w-600);
  color: var(--color-primary);
  background: var(--color-active-bg);
  border: var(--color-hairline);
  border-radius: var(--radius-pill);
  padding: 9px 16px;
  text-decoration: none;
  transition: background 0.2s ease;
}

.item__action:hover {
  background: var(--color-canvas-soft);
}

.item__action svg {
  width: 16px;
  height: 16px;
}
</style>